In [6]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

In [1]:
import pandas as pd
books = pd.read_csv("books_cleaned.csv")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web - A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5083,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5084,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5085,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5086,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that - Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5087,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [2]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5083    9788172235222 On A Train Journey Home To North...
5084    9788173031014 This book tells the tale of a ma...
5085    9788179921623 Wisdom to Create a Life of Passi...
5086    9788185300535 This collection of the timeless ...
5087    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5088, dtype: object

In [17]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   sep="\n",
                                   header=False,
                                   index=False)

In [7]:
raw_documents = TextLoader("tagged_description.txt",  encoding='utf-8').load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 373, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 482, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 188, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 211, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 513, which is longer than the specified 0
Created a chunk of size 752, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 728, which is longer than the specified 0
Created a chunk of size 721, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 473, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 681, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 553, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 787, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 533, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 563, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 410, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 595, which is longer than the specified 0
Created a chunk of size 476, which is longer than the specified 0
Created a chunk of size 459, which is longer than the specified 0
Created a chunk of size 257, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 614, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 887, which is longer than the specified 0
Created a chunk of size 693, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 479, which is longer than the specified 0
Created a chunk of size 300, which is longer than the specified 0
Created a chunk of size 520, which is longer than the specified 0
Created a chunk of size 647, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 686, which is longer than the specified 0
Created a chunk of size 548, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 406, which is longer than the specified 0
Created a chunk of size 1184, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 1057, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 417, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 526, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 899, which is longer than the specified 0
Created a chunk of size 1270, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 1635, which is longer than the specified 0
Created a chunk of size 436, which is longer than the specified 0
Created a chunk of size 249, which is longer than the specified 0
Created a chunk of size 777, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 514, which is longer than the specified 0
Created a chunk of size 958, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 851, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1119, which is longer than the specified 0
Created a chunk of size 836, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 235, which is longer than the specified 0
Created a chunk of size 732, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 773, which is longer than the specified 0
Created a chunk of size 278, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 445, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 912, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 844, which is longer than the specified 0
Created a chunk of size 1126, which is longer than the specified 0
Created a chunk of size 1073, which is longer than the specified 0
Created a chunk of size 1318, which is longer than the specified 0
Created a chunk of size 361, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 240, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1141, which is longer than the specified 0
Created a chunk of size 1004, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 954, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 639, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 793, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 254, which is longer than the specified 0
Created a chunk of size 1422, which is longer than the specified 0
Created a chunk of size 1083, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 806, which is longer than the specified 0
Created a chunk of size 1812, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1180, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 1642, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 1930, which is longer than the specified 0
Created a chunk of size 872, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 577, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 1142, which is longer than the specified 0
Created a chunk of size 557, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 221, which is longer than the specified 0
Created a chunk of size 1135, which is longer than the specified 0
Created a chunk of size 722, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 765, which is longer than the specified 0
Created a chunk of size 606, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 857, which is longer than the specified 0
Created a chunk of size 1032, which is longer than the specified 0
Created a chunk of size 189, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 495, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 348, which is longer than the specified 0
Created a chunk of size 733, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 1015, which is longer than the specified 0
Created a chunk of size 970, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 544, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 207, which is longer than the specified 0
Created a chunk of size 376, which is longer than the specified 0
Created a chunk of size 931, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 854, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 324, which is longer than the specified 0
Created a chunk of size 241, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 704, which is longer than the specified 0
Created a chunk of size 1912, which is longer than the specified 0
Created a chunk of size 395, which is longer than the specified 0
Created a chunk of size 485, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 556, which is longer than the specified 0
Created a chunk of size 386, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 425, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 624, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 994, which is longer than the specified 0
Created a chunk of size 847, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 336, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2030, which is longer than the specified 0
Created a chunk of size 396, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 698, which is longer than the specified 0
Created a chunk of size 822, which is longer than the specified 0
Created a chunk of size 354, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 195, which is longer than the specified 0
Created a chunk of size 508, which is longer than the specified 0
Created a chunk of size 663, which is longer than the specified 0
Created a chunk of size 1282, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1056, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 269, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 225, which is longer than the specified 0
Created a chunk of size 222, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 969, which is longer than the specified 0
Created a chunk of size 613, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 289, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 963, which is longer than the specified 0
Created a chunk of size 232, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 786, which is longer than the specified 0
Created a chunk of size 648, which is longer than the specified 0
Created a chunk of size 984, which is longer than the specified 0
Created a chunk of size 799, which is longer than the specified 0
Created a chunk of size 193, which is longer than the specified 0
Created a chunk of size 1163, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0
Created a chunk of size 246, which is longer than the specified 0
Created a chunk of size 875, which is longer than the specified 0
Created a chunk of size 817, which is longer than the specified 0

In [9]:
documents[88]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780060004507 An adaptation of the original story follows the activities of seven children in nineteenth-century New England as they prepare for the Thanksgiving holiday while Mother is away caring for Grandmother.')

In [10]:
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
db_books = Chroma.from_documents(
    documents,
    embedding=embedding_model
)

In [11]:
query = " a book to teach children about roman history"
docs = db_books.similarity_search(query, k=10)
docs

[Document(id='f3b42b02-fbb8-4b65-8845-0a4aaa42fa10', metadata={'source': 'tagged_description.txt'}, page_content="9780192833006 Cornelius Tacitus, Rome's greatest historian, was inspired to take up his pen when the assassination of Domitian ended `fifteen years of enforced silence'. Agricola is the biography of his late father-in-law and an account of Roman Britain. Germania gives insight into Rome's most dangerous enemies, the Germans, and is the only surviving specimen from the ancient world of an ethnographic study. Each in its way has had immense influence on our perception of Rome and the northern `barbarians' and the edition reflects recent research in Roman-British and Roman-German history. - ;`Long may the barbarians continue, I pray, if not to love us, at least to hate one another.' Cornelius Tacitus, Rome's greatest historian and the last great writer of classical Latin prose, produced his first two books in AD 98. He was inspired to take up his pen when the assassination of Domitian ended `fifteen years of enforced silence'. The first products were brief: the biography of his late father-in-law Julius Agricola and an account of Rome's most dangerous enemies, the Germans. Since Agricola's claim to fame was that as governor for seven years he had completed the conquest of Britain, begun four decades earlier, much of the first work is devoted to Britain and its people. The second is the only surviving specimen from the ancient world of an ethnographic study. Each in its way has had immense influence on our perception of Rome and the northern `barbarians'. This edition reflects recent research in Roman-British and Roman-German history and includes newly discovered evidence on Tacitus' early career. -"),
 Document(id='2ba2df09-4622-4ca6-b048-8a11fceade96', metadata={'source': 'tagged_description.txt'}, page_content='9780380710843 The fourth novel of the Masters of Rome series focuses on the women in the life of the Roman emperor Gaius Julius Caesar at the height of his power'),
 Document(id='e5af32eb-a1f2-4add-af41-b08c50725e99', metadata={'source': 'tagged_description.txt'}, page_content='"9780671024208 Now in paperback--the sweeping epic of ancient Rome from the #1 bestselling author of ""The Thorn Birds"" that brings to life Gaius Julius Caesar during the last days of the Roman Republic."'),
 Document(id='27262e59-740b-4333-979b-0cfb468b03ed', metadata={'source': 'tagged_description.txt'}, page_content='9780375727061 An insightful historical novel recreates the brief but brilliant career of Julian, the Roman emperor and philosopher who dedicated himself to the restoration of Hellenism and tried to halt the spread of Christianity. Reprint.'),
 Document(id='80ab606b-70ea-47c7-88e3-202352b132ce', metadata={'source': 'tagged_description.txt'}, page_content="9780760768952 Among the most durable and engaging texts in world literature, Julius Caesar's Conquest of Gaul tells how he and his legions conquered much of modern France in less than a decade (58-51 BCE), despite determined resistance. Perhaps the most famous Roman ever, Gaius Julius Caesar created a legacy which has resonated, for good or ill, throughout Western culture. Architect of an imperial system, eponymous sponsor of a reformed calendar system, orator second only to Cicero, conqueror of Gaul: Surely those accomplishments in the diverse fields of politics, applied mathematics, rhetoric, and military science would justify his eminence. Nevertheless, the high literary quality and historical value of this seemingly modest account match its exciting story of diplomatic maneuverings, shifting alliances, and military actions; the final chapters culminate in the revolt of the united Gallic tribes under Vercingetorix, France's first national hero, and are as compelling as any contemporary spy thriller."),
 Document(id='84ff6193-802b-4f9b-bb0b-00c93306ee47', metadata={'source': 'tagged_description.txt'}, page_content='9780679724773 The emperor Claudius tells of his life during the reigns of Augustus, Tiberius, and Caligula and the events that led to his rise to power in a classic novel reconstructing ancient Rome'),
 Document(id='c087f60a-7373-4205-9f9b-c390a2791375', metadata={'source': 'tagged_description.txt'}, page_content='9781565849426 Parenti presents a story of popular resistance against entrenched power and wealth. As he carefully weighs the evidence in the murder of Caesar, he sketches in the background to the crime with fascinating detail about Roman society.'),
 Document(id='5fc6fa8b-6c14-4b7f-8e16-57632836c3d9', metadata={'source': 'tagged_description.txt'}, page_content='9780688093686 A story tracing the creation of Republican Rome presents those who founded an empire, including Marius and Sulla, each determined to become the First Man of Rome'),
 Document(id='19b65722-5585-4fbc-a3d2-87f3c8463570', metadata={'source': 'tagged_description.txt'}, page_content='9780451528308 From ancient Greece to 19th-century America, this collection traces the history of civilization through the seminal works of its most influential thinkers including Plato, Aristotle, St. Thomas Aquinas, John Stuart Mill, and others.'),
 Document(id='c0be3d76-bcc9-4dd6-bba8-9b46cce079a8', metadata={'source': 'tagged_description.txt'}, page_content='"9781573229869 An ancient manuscript called ""The Dream of Scipio"" links three separate centuries--the fifth, the end of the Roman Empire; the fourteenth, the time of the Black Death; and the twentieth during World War II--and three stories of love, all set in Provence."')]

In [12]:
books[books["isbn13"] ==int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
945,9780192833006,0192833006,Agricola and Germany,Tacitus,Literary Collections,http://books.google.com/books/content?id=wS7IJ...,"Cornelius Tacitus, Rome's greatest historian, ...",1999.0,3.98,224.0,25.0,Agricola and Germany,"9780192833006 Cornelius Tacitus, Rome's greate..."

In [15]:
def retrieve_semantic_recommendationv(
        query: str,
        top_k: int = 10) -> pd.DataFrame:
        recs = db_books.similarity_search(query, k = 50)

        book_list = []
        for i in range (0 , len(recs)):
            book_list+=[int(recs[i].page_content.strip('"' ).split()[0])]

        return books[books["isbn13"].isin(book_list)].head(top_k)

In [16]:
retrieve_semantic_recommendationv("lesbian romance", 5)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
155,9780060574215,0060574216,"Men Are from Mars, Women Are from Venus",John Gray,Family & Relationships,http://books.google.com/books/content?id=MUw_d...,Rediscover the most famous relationship book e...,2004.0,3.54,368.0,126108.0,"Men Are from Mars, Women Are from Venus - The ...",9780060574215 Rediscover the most famous relat...
177,9780060598846,0060598840,Love Overboard,Janet Evanovich,Fiction,http://books.google.com/books/content?id=5pClJ...,"Dear Reader: In a previous life, before the ti...",2005.0,3.65,244.0,11223.0,Love Overboard,"9780060598846 Dear Reader: In a previous life,..."
209,9780060753634,0060753633,Mating in Captivity,Esther Perel,Psychology,http://books.google.com/books/content?id=-HIhM...,A guide for loving couples who are looking to ...,2006.0,4.13,272.0,7699.0,Mating in Captivity - Reconciling the Erotic a...,9780060753634 A guide for loving couples who a...
259,9780060854096,006085409X,Dates From Hell,Kim Harrison;Lynsay Sands;Kelley Armstrong;Lor...,Fiction,http://books.google.com/books/content?id=D07pn...,She thought her date was out of this world. Ac...,2006.0,3.78,416.0,10467.0,Dates From Hell,9780060854096 She thought her date was out of ...
282,9780060916466,006091646X,The Dance of Intimacy,Harriet Lerner,Psychology,http://books.google.com/books/content?id=tTKc8...,"In The Dance of Intimacy, the bestselling auth...",1990.0,4.06,255.0,7128.0,The Dance of Intimacy - A Woman's Guide to Cou...,"9780060916466 In The Dance of Intimacy, the be..."

In [17]:
from transformers import pipeline
fiction_categories = ["fiction" "non-fiction "]


pipe = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0)

Device set to use cpu

In [19]:
books.loc[books["simple_categories"] == "fiction", "description"].reset_index(drop=True)[0]

KeyError: 'simple_categories'